// Exhaustive input->output AGI audit: attribute every line to its enclosing function + pipeline stage,
// then enumerate EVERY instance of handed-perception, magic-number-in-logic, and scripted-decision.
const fs=require('fs');
const path='D:/code/Tami/.opus-tools/agi_proto/starfighter/starfighter.html';
const html=fs.readFileSync(path,'utf8');
const scriptStart=html.indexOf('<script>', html.indexOf('three.min.js'))>=0 ? 0:0;
const m=html.match(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/i);
const src=m[1];
// line offset of the inline script within the file, so we report FILE line numbers
const fileLineOffset=html.slice(0, html.indexOf(m[1])).split('\n').length; // 1-based line where script body starts
const lines=src.split('\n');

// ---- pipeline-stage map (function -> stage) ----
const STAGE={
  // 1 INPUT / perception (gather raw world state)
  nearestRival:'1-PERCEPTION', weakestEnemyNear:'1-PERCEPTION', nearestOf:'1-PERCEPTION', nearestPlanet:'1-PERCEPTION',
  nearestHostileNear:'1-PERCEPTION', shipSituation:'1-PERCEPTION', tomCandidates:'1-PERCEPTION', threatOf:'1-PERCEPTION',
  // 2 HYPOTHESES / scoring
  rayScore:'2-SCORING', decideByRays:'2-SCORING', tomPredict:'2-SCORING', pickTarget:'2-SCORING', chooseUpgrade:'2-SCORING',
  // 3 POLICY / decision
  think:'3-POLICY', applyCommand:'3-POLICY', doTrade:'3-POLICY', planetDefense:'3-POLICY', warTick:'3-POLICY',
  // 4 CONTROL / actuation
  aimAt:'4-CONTROL', flyStep:'4-CONTROL', adaptNav:'4-CONTROL',
  // 5 OUTPUT / effects + learn signals
  reasonChain:'5-EXPLAIN', broadcast:'5-COMMS', langEpisode:'5-LEARN', tomSample:'5-LEARN', rayQSample:'5-LEARN',
};
function stageOf(fn){ return STAGE[fn]||'other'; }

// ---- track enclosing top-level function per line ----
let cur='<top>';
const decl=/^function\s+(\w+)\s*\(/;   // only column-0 top-level function declarations (inner const/let don't reset attribution)
const learnedRe=/\bLANG\b|\bnavGain\b|\bTOM\b|\bRAYQ\b|langPick|tomPredict|rayScore|decideByRays|langScore|adaptNav/;
const rawStateRe=/\.distanceTo\(|\.pos\b|\.hp\b|\.vel\b|\.alive\b|\.maxHp\b|\.credits\b|\.quat\b/g;
const cmpRe=/[<>]=?|===|!==/;

const perception=[], magic=[], decisions=[], learnedTouch=[];
lines.forEach((ln,i)=>{
  const d=ln.match(decl); if(d){ cur=d[1]||d[2]; }
  const fileLine=fileLineOffset+i;
  const stage=stageOf(cur);
  const codeTrim=ln.trim();
  if(!codeTrim||codeTrim.startsWith('//')) return;

  // handed perception: raw-state reads inside agent-pipeline functions (stages 1-5, not <top>/render/other engine)
  if(stage!=='other'){ const rs=(ln.match(rawStateRe)||[]); if(rs.length){ perception.push({stage,fn:cur,line:fileLine,reads:rs.length,code:codeTrim.slice(0,110)}); } }

  // magic numbers in LOGIC: a numeric literal (not 0/1, not part of CFG.NAME) on a line with a comparison or *scale, inside agent functions
  if(stage!=='other'){
    const stripped=ln.replace(/CFG\.[A-Z_0-9]+/g,'').replace(/0x[0-9a-fA-F]+/g,'');
    const nums=(stripped.match(/(?<![\w.$])\d+\.?\d*/g)||[]).filter(n=>!/^[01]$/.test(n));
    if(nums.length && (cmpRe.test(ln)||/\*\s*\d/.test(stripped)||/\d\s*\*/.test(stripped))) magic.push({stage,fn:cur,line:fileLine,nums,code:codeTrim.slice(0,110)});
  }

  // scripted decisions: mode assignments + hardcoded target/threshold branches
  if(/\bmode\s*=\s*['"][A-Z]/.test(ln)) decisions.push({stage,fn:cur,line:fileLine,code:codeTrim.slice(0,110)});

  // learned-state touchpoints
  if(learnedRe.test(ln)) learnedTouch.push({stage,fn:cur,line:fileLine,code:codeTrim.slice(0,100)});
});

// ---- write full enumeration to markdown ----
function section(title,arr,fmt){ let s='\n## '+title+' — '+arr.length+' instances\n\n'; const byStage={};
  arr.forEach(x=>{ (byStage[x.stage]=byStage[x.stage]||[]).push(x); });
  Object.keys(byStage).sort().forEach(st=>{ s+='### '+st+' ('+byStage[st].length+')\n'; byStage[st].forEach(x=>{ s+='- `'+x.fn+'` L'+x.line+' — '+fmt(x)+'\n'; }); s+='\n'; });
  return s; }
let out='# Starfighter — exhaustive input→output AGI audit (every instance)\n\nGenerated by `scratchpad/agi_trace.js`. File-line numbers into `starfighter.html`.\n';
out+='\nPipeline: **1-PERCEPTION → 2-SCORING → 3-POLICY → 4-CONTROL → 5-EXPLAIN/COMMS/LEARN**.\n';
out+=section('HANDED PERCEPTION (raw global state read with zero sensing/noise/occlusion)', perception, x=>x.reads+' raw read(s): `'+x.code+'`');
out+=section('MAGIC NUMBERS IN LOGIC (should be named CFG consts)', magic, x=>'['+x.nums.join(',')+'] `'+x.code+'`');
out+=section('SCRIPTED MODE DECISIONS (authored, not learned)', decisions, x=>'`'+x.code+'`');
out+=section('LEARNED-STATE TOUCHPOINTS (the whole learned surface)', learnedTouch, x=>'`'+x.code+'`');
fs.writeFileSync('D:/code/Tami/.opus-tools/agi_proto/starfighter/AGI_AUDIT_INSTANCES.md', out);

// ---- console summary by stage ----
const sum={};
[['perception',perception],['magic',magic],['decisions',decisions]].forEach(([k,arr])=>{ arr.forEach(x=>{ sum[x.stage]=sum[x.stage]||{}; sum[x.stage][k]=(sum[x.stage][k]||0)+1; }); });
console.log(JSON.stringify({
  totals:{ handed_perception_reads: perception.reduce((a,x)=>a+x.reads,0), perception_sites:perception.length, magic_in_logic:magic.length, scripted_mode_decisions:decisions.length, learned_touchpoints:learnedTouch.length },
  by_pipeline_stage: sum,
  learned_functions: [...new Set(learnedTouch.map(x=>x.fn))],
  full_enumeration:'AGI_AUDIT_INSTANCES.md'
},null,1));
